### PR TITLE
Add spaces to italic parts of readme

### PR DESCRIPTION
**Pull request by flying-sheep**
### Checklist

* [x] I have read the [Contributor Guide](../../CONTRIBUTING.md)
* [x] I have read and agree to the [Code of Conduct](../../CODE_OF_CONDUCT.md)
* [x] I have added a description of my changes and why I'd like them included in the section below

### Description of Changes

Just a small readability fix for the readme: An italic section was missing some spaces:

> *an*uninit*piece of memory is not simply*an arbitrary bit pattern,*it is a wholly separate state*

→

> *an* uninit *piece of memory is not simply* an arbitrary bit pattern, *it is a wholly separate state*

### CODE REVIEW

**Review by fu5ha — APPROVED** [review]
Thanks!

**Comment by fu5ha** [comment]
Yay! The mergify config works too :)

**Comment by flying-sheep** [comment]
Ha, happy to be of service to test your bot setup with a trivial commit :D

I wish I knew a good way to test this stuff without messing up my repos with “test commit/comment/PR, please ignore” :thinking:

**Comment by fu5ha** [comment]
Ha, that's what I usually do. I guess could have a separate repo that you completely overwrite with the same config to test with but 🤷‍♀️ seems like work to me ;p

**Pull request merged**
